# Generated by Django 5.1.1 on 2024-10-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Artista', '0003_artista_invitado_email_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_votos', models.PositiveIntegerField(default=0)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Artista.artista_invitado')),
            ],
        ),
    ]
